#!/bin/sh
version=$(rpm -q --qf '%{version}' system-release)
cat << EOF
   ___   ___ _____ ___  ___  ___  ___   _   __  __ ___ 
  / _ \ / __|_   _/ _ \| _ \/ _ \|   \ /_\ |  \/  |_ _| ®
 | (_) | (__  | || (_) |  _/ (_) | |) / _ \| |\/| || | 
  \___/ \___| |_| \___/|_|  \___/|___/_/ \_\_|  |_|___|

https://aws.amazon.com/amazon-linux-ami/$version-release-notes/
EOF
