#!/bin/sh
version=$(rpm -q --qf '%{version}' system-release)
cat << EOF
      _                 _                  
  ___| | ___  _   _  __| | ___ _   _  __ _ 
 / __| |/ _ \| | | |/ _` |/ _ \ | | |/ _` | ®
| (__| | (_) | |_| | (_| |  __/ |_| | (_| |
 \___|_|\___/ \__,_|\__,_|\___|\__, |\__,_|
                               |___/ 

https://aws.amazon.com/amazon-linux-ami/$version-release-notes/
EOF
